apiVersion: v2
name: everest-db-namespace
description: A sub-chart for provisioning Everest DB namespaces.
type: application
version: 0.0.0
appVersion: 0.0.0
kubeVersion: '>= 1.27.0'
dependencies:
  - name: common
    version: 0.0.*
    repository: "file://../common"
