{{- if (and (not .Values.compatibility.openshift) .Values.olm.install) }}
kind: ServiceAccount
apiVersion: v1
metadata:
  name: olm-operator-serviceaccount
  namespace: {{ include "everest.olmNamespace" . }}
{{- end }}
